### ISSUE TITLE
各メッセージを外部に出す

### ISSUE THREAD

**Issue by eigorian** [eigorian/gerrit-slack#2]
notification.yml を拡張して、ここにメッセージを指定できるようにしようと思う

``` yml
gerritSlack:
  plus_two:
    destination: group
    message: "#{update.author_slack_name} has *+2'd* #{update.commit}: ready for *QA*"
```
